# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Version1.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(784, 647)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 6, 1, 1)
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 0, 0, 1, 10)
        self.verticalScrollBar = QtWidgets.QScrollBar(self.centralwidget)
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.gridLayout.addWidget(self.verticalScrollBar, 0, 10, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.zoomSlider = QtWidgets.QSlider(self.centralwidget)
        self.zoomSlider.setOrientation(QtCore.Qt.Horizontal)
        self.zoomSlider.setObjectName("zoomSlider")
        self.gridLayout.addWidget(self.zoomSlider, 1, 5, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 1, 3, 1, 1)
        self.searchEditor = QtWidgets.QLineEdit(self.centralwidget)
        self.searchEditor.setObjectName("searchEditor")
        self.gridLayout.addWidget(self.searchEditor, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 9, 1, 1)
        self.lineNo = QtWidgets.QLCDNumber(self.centralwidget)
        self.lineNo.setObjectName("lineNo")
        self.gridLayout.addWidget(self.lineNo, 1, 7, 1, 1)
        self.wordNo = QtWidgets.QLCDNumber(self.centralwidget)
        self.wordNo.setObjectName("wordNo")
        self.gridLayout.addWidget(self.wordNo, 1, 8, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 784, 31))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuFormat = QtWidgets.QMenu(self.menubar)
        self.menuFormat.setObjectName("menuFormat")
        self.menuInsert = QtWidgets.QMenu(self.menubar)
        self.menuInsert.setObjectName("menuInsert")
        self.menuOutput = QtWidgets.QMenu(self.menubar)
        self.menuOutput.setObjectName("menuOutput")
        self.menuSearch = QtWidgets.QMenu(self.menubar)
        self.menuSearch.setObjectName("menuSearch")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        MainWindow.insertToolBarBreak(self.toolBar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/win/filenew.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNew.setIcon(icon)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/win/fileopen.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon1)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/win/filesave.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon2)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/win/editundo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUndo.setIcon(icon3)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/win/editredo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRedo.setIcon(icon4)
        self.actionRedo.setObjectName("actionRedo")
        self.actionCut = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/win/editcut.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCut.setIcon(icon5)
        self.actionCut.setObjectName("actionCut")
        self.actionCopy = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/win/editcopy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCopy.setIcon(icon6)
        self.actionCopy.setObjectName("actionCopy")
        self.actionPaste = QtWidgets.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/win/editpaste.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPaste.setIcon(icon7)
        self.actionPaste.setObjectName("actionPaste")
        self.actionSpell_Check = QtWidgets.QAction(MainWindow)
        self.actionSpell_Check.setObjectName("actionSpell_Check")
        self.actionFont = QtWidgets.QAction(MainWindow)
        self.actionFont.setObjectName("actionFont")
        self.actionBold = QtWidgets.QAction(MainWindow)
        self.actionBold.setCheckable(True)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/win/textbold.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBold.setIcon(icon8)
        self.actionBold.setObjectName("actionBold")
        self.actionItalics = QtWidgets.QAction(MainWindow)
        self.actionItalics.setCheckable(True)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/images/win/textitalic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionItalics.setIcon(icon9)
        self.actionItalics.setObjectName("actionItalics")
        self.actionUnderline = QtWidgets.QAction(MainWindow)
        self.actionUnderline.setCheckable(True)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/images/win/textunder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUnderline.setIcon(icon10)
        self.actionUnderline.setObjectName("actionUnderline")
        self.actionCenter_Align = QtWidgets.QAction(MainWindow)
        self.actionCenter_Align.setCheckable(True)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/images/win/textcenter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCenter_Align.setIcon(icon11)
        self.actionCenter_Align.setObjectName("actionCenter_Align")
        self.actionLeft_Align = QtWidgets.QAction(MainWindow)
        self.actionLeft_Align.setCheckable(True)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/images/win/textleft.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionLeft_Align.setIcon(icon12)
        self.actionLeft_Align.setObjectName("actionLeft_Align")
        self.actionRight_Align = QtWidgets.QAction(MainWindow)
        self.actionRight_Align.setCheckable(True)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/images/win/textright.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRight_Align.setIcon(icon13)
        self.actionRight_Align.setObjectName("actionRight_Align")
        self.actionJustified_Align = QtWidgets.QAction(MainWindow)
        self.actionJustified_Align.setCheckable(True)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/images/win/textjustify.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionJustified_Align.setIcon(icon14)
        self.actionJustified_Align.setObjectName("actionJustified_Align")
        self.actionImage = QtWidgets.QAction(MainWindow)
        self.actionImage.setObjectName("actionImage")
        self.actionBox = QtWidgets.QAction(MainWindow)
        self.actionBox.setObjectName("actionBox")
        self.actionCell = QtWidgets.QAction(MainWindow)
        self.actionCell.setObjectName("actionCell")
        self.actionHTML = QtWidgets.QAction(MainWindow)
        self.actionHTML.setObjectName("actionHTML")
        self.actionTeX = QtWidgets.QAction(MainWindow)
        self.actionTeX.setObjectName("actionTeX")
        self.actionPDF = QtWidgets.QAction(MainWindow)
        self.actionPDF.setObjectName("actionPDF")
        self.actionFind = QtWidgets.QAction(MainWindow)
        self.actionFind.setObjectName("actionFind")
        self.actionFind_all = QtWidgets.QAction(MainWindow)
        self.actionFind_all.setObjectName("actionFind_all")
        self.actionReplace = QtWidgets.QAction(MainWindow)
        self.actionReplace.setObjectName("actionReplace")
        self.actionCount = QtWidgets.QAction(MainWindow)
        self.actionCount.setObjectName("actionCount")
        self.actionSearch_Command = QtWidgets.QAction(MainWindow)
        self.actionSearch_Command.setObjectName("actionSearch_Command")
        self.actionGeneral_Help = QtWidgets.QAction(MainWindow)
        self.actionGeneral_Help.setObjectName("actionGeneral_Help")
        self.actionWhy_to_use = QtWidgets.QAction(MainWindow)
        self.actionWhy_to_use.setObjectName("actionWhy_to_use")
        self.actionWhy_not_to_use = QtWidgets.QAction(MainWindow)
        self.actionWhy_not_to_use.setObjectName("actionWhy_not_to_use")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionSpell_Check)
        self.menuFormat.addAction(self.actionFont)
        self.menuFormat.addSeparator()
        self.menuFormat.addAction(self.actionBold)
        self.menuFormat.addAction(self.actionItalics)
        self.menuFormat.addAction(self.actionUnderline)
        self.menuFormat.addSeparator()
        self.menuFormat.addAction(self.actionCenter_Align)
        self.menuFormat.addAction(self.actionLeft_Align)
        self.menuFormat.addAction(self.actionRight_Align)
        self.menuFormat.addAction(self.actionJustified_Align)
        self.menuInsert.addAction(self.actionImage)
        self.menuInsert.addAction(self.actionBox)
        self.menuInsert.addAction(self.actionCell)
        self.menuOutput.addAction(self.actionHTML)
        self.menuOutput.addAction(self.actionTeX)
        self.menuOutput.addAction(self.actionPDF)
        self.menuSearch.addAction(self.actionFind)
        self.menuSearch.addAction(self.actionFind_all)
        self.menuSearch.addAction(self.actionReplace)
        self.menuSearch.addAction(self.actionCount)
        self.menuHelp.addAction(self.actionSearch_Command)
        self.menuHelp.addAction(self.actionGeneral_Help)
        self.menuHelp.addAction(self.actionWhy_to_use)
        self.menuHelp.addAction(self.actionWhy_not_to_use)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuFormat.menuAction())
        self.menubar.addAction(self.menuInsert.menuAction())
        self.menubar.addAction(self.menuSearch.menuAction())
        self.menubar.addAction(self.menuOutput.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.toolBar.addAction(self.actionNew)
        self.toolBar.addAction(self.actionSave)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionBold)
        self.toolBar.addAction(self.actionItalics)
        self.toolBar.addAction(self.actionUnderline)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCenter_Align)
        self.toolBar.addAction(self.actionLeft_Align)
        self.toolBar.addAction(self.actionRight_Align)
        self.toolBar.addAction(self.actionJustified_Align)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionHTML)
        self.toolBar.addAction(self.actionTeX)
        self.toolBar.addAction(self.actionPDF)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Find"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuFormat.setTitle(_translate("MainWindow", "Format"))
        self.menuInsert.setTitle(_translate("MainWindow", "Insert"))
        self.menuOutput.setTitle(_translate("MainWindow", "Output"))
        self.menuSearch.setTitle(_translate("MainWindow", "Search"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionRedo.setShortcut(_translate("MainWindow", "Ctrl+Y"))
        self.actionCut.setText(_translate("MainWindow", "Cut"))
        self.actionCut.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionCopy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionPaste.setText(_translate("MainWindow", "Paste"))
        self.actionPaste.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionSpell_Check.setText(_translate("MainWindow", "Spell Check"))
        self.actionFont.setText(_translate("MainWindow", "Font"))
        self.actionBold.setText(_translate("MainWindow", "Bold"))
        self.actionBold.setShortcut(_translate("MainWindow", "Ctrl+B"))
        self.actionItalics.setText(_translate("MainWindow", "Italics"))
        self.actionItalics.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.actionUnderline.setText(_translate("MainWindow", "Underline"))
        self.actionUnderline.setShortcut(_translate("MainWindow", "Ctrl+U"))
        self.actionCenter_Align.setText(_translate("MainWindow", "Center Align"))
        self.actionCenter_Align.setShortcut(_translate("MainWindow", "Ctrl+E"))
        self.actionLeft_Align.setText(_translate("MainWindow", "Left Align"))
        self.actionLeft_Align.setShortcut(_translate("MainWindow", "Ctrl+L"))
        self.actionRight_Align.setText(_translate("MainWindow", "Right Align"))
        self.actionRight_Align.setShortcut(_translate("MainWindow", "Ctrl+R"))
        self.actionJustified_Align.setText(_translate("MainWindow", "Justified Align"))
        self.actionJustified_Align.setShortcut(_translate("MainWindow", "Ctrl+J"))
        self.actionImage.setText(_translate("MainWindow", "Image"))
        self.actionBox.setText(_translate("MainWindow", "Box"))
        self.actionCell.setText(_translate("MainWindow", "Table"))
        self.actionHTML.setText(_translate("MainWindow", "HTML"))
        self.actionTeX.setText(_translate("MainWindow", "TeX"))
        self.actionPDF.setText(_translate("MainWindow", "PDF"))
        self.actionFind.setText(_translate("MainWindow", "Find"))
        self.actionFind.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.actionFind_all.setText(_translate("MainWindow", "Find all"))
        self.actionReplace.setText(_translate("MainWindow", "Replace"))
        self.actionCount.setText(_translate("MainWindow", "Count"))
        self.actionSearch_Command.setText(_translate("MainWindow", "Search Command"))
        self.actionGeneral_Help.setText(_translate("MainWindow", "General Help"))
        self.actionWhy_to_use.setText(_translate("MainWindow", "Why to use?"))
        self.actionWhy_not_to_use.setText(_translate("MainWindow", "Why not to use?"))
        self.actionAbout.setText(_translate("MainWindow", "About"))

import diagramscene_rc
import textedit_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

